export const URLS = {
    sign_in: 'api/auth/sign-in',
    category_get_all: '/api/category/get-all',
    category_get_one: '/api/category/get',
    category_add: '/api/category/add',
    category_delete: '/api/category/delete',
    category_edit: '/api/category/edit',
    seller_get_all: '/api/seller/get-all',
    seller_get_one: '/api/seller/get',
    seller_add: '/api/seller/add',
    seller_delete: '/api/seller/delete',
    seller_edit: '/api/seller/edit',
    product_get_all: '/api/product/get-all',
    product_get_one: '/api/product/get-by-id',
    product_add: '/api/product/add',
    product_delete: '/api/product/delete',
    product_edit: '/api/product/edit',
    translations_list: '/api/lang/all',
    translations_edit: '/api/lang/create-edit',
    image_upload: '/api/images/upload',
    users_get_all: "/api/users/get-all",
    users_ban: "/api/users/ban",
    users_unban: "/api/users/unban",
    get_price_status: '/api/priceStatus/get-all',
    get_price_history: '/api/price-history/get-all',
};
